---
- hosts: localhost
  connection: local
  become: no
  vars_prompt:
    - name: yn_gpu
      prompt: "Would you like to install the optional GPU modules (cuda: 10.2, cudnn: 7.6.5, TensorRT: 7.0.0)? (y/n)"
      default: "y"
      private: no
  pre_tasks:
    - pause:
        seconds: 10
        prompt: "[Warning]: Skipping installation of GPU modules. To execute nodes depending on TensorRT, please manually install the modules listed above."
      when: yn_gpu != 'y'
  roles:
    - { role: cuda, when: yn_gpu == 'y' }
    - { role: tensorrt, when: yn_gpu == 'y' }
    - { role: ros, release: melodic }
    - osqp
    - { role: autoware, rosdistro: melodic }
    - { role: pacmod, rosdistro: melodic }
